name: Build and Release

on:
  push:
    branches:
      - master  # Runs only when code is pushed to the master branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24  # Use your desired Go version

      - name: Build the Go project
        run: |
          mkdir -p releases
          GOOS=linux GOARCH=amd64 go build -o releases/route-rover

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_SECRET }}
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: releases/route-rover
